#!/bin/bash

echo "🔍 DIAGNOSING SERVER ISSUES"
echo "==========================="

echo "SSH into server and run these commands:"
echo ""
echo "ssh root@143.244.133.154"
echo ""
echo "Then run:"
echo "1. Check PM2 status:"
echo "   pm2 status"
echo ""
echo "2. Check PM2 logs:"
echo "   pm2 logs --lines 20"
echo ""
echo "3. Check what ports are running:"
echo "   netstat -tlnp | grep :3000"
echo "   netstat -tlnp | grep :8080" 
echo ""
echo "4. Check nginx config:"
echo "   nginx -t"
echo "   systemctl status nginx"
echo ""
echo "5. Test services directly:"
echo "   curl localhost:3000"
echo "   curl localhost:8080"
echo ""
echo "6. If services are on wrong ports, check the actual server.js files:"
echo "   cat /var/www/search-proxy-v2/server.js | grep listen"
echo "   cat /var/www/ic-proxy-v2/server.js | grep listen"