#!/bin/bash

echo "🔄 CYCLE RECOVERY SCRIPT"
echo "========================"
echo ""
echo "💰 OLD CANISTERS WITH CYCLES:"
echo "1. Old Admin Backend: szqyk-3aaaa-aaaaj-az4sa-cai (4.2T cycles)"
echo "2. Old Consumer: tgyl5-yyaaa-aaaaj-az4wq-cai (4.1T cycles)"
echo ""
echo "📦 NEW CANISTERS TO RECEIVE CYCLES:"
echo "1. New Admin Backend: wvset-niaaa-aaaao-a4osa-cai"
echo "2. New Consumer: t3pjp-kqaaa-aaaao-a4ooq-cai"
echo ""
echo "⚠️  IMPORTANT: Run these commands to recover your cycles!"
echo ""

echo "STEP 1: Withdraw cycles from old admin canister"
echo "-----------------------------------------------"
echo "dfx canister call szqyk-3aaaa-aaaaj-az4sa-cai wallet_balance --network ic"
echo "dfx canister deposit-cycles 4000000000000 wvset-niaaa-aaaao-a4osa-cai --network ic --with-cycles szqyk-3aaaa-aaaaj-az4sa-cai"
echo ""

echo "STEP 2: Withdraw cycles from old consumer canister"
echo "--------------------------------------------------"
echo "dfx canister call tgyl5-yyaaa-aaaaj-az4wq-cai wallet_balance --network ic"
echo "dfx canister deposit-cycles 4000000000000 t3pjp-kqaaa-aaaao-a4ooq-cai --network ic --with-cycles tgyl5-yyaaa-aaaaj-az4wq-cai"
echo ""

echo "STEP 3: Stop and delete old canisters (after cycle transfer)"
echo "------------------------------------------------------------"
echo "dfx canister stop szqyk-3aaaa-aaaaj-az4sa-cai --network ic"
echo "dfx canister delete szqyk-3aaaa-aaaaj-az4sa-cai --network ic"
echo "dfx canister stop tgyl5-yyaaa-aaaaj-az4wq-cai --network ic"
echo "dfx canister delete tgyl5-yyaaa-aaaaj-az4wq-cai --network ic"
echo ""

echo "⚠️  AUTH CANISTER INFO:"
echo "----------------------"
echo "The auth canister (rdmx6-jaaaa-aaaaa-aaadq-cai) is used for:"
echo "1. Internet Identity authentication"
echo "2. Managing user sessions in the admin dashboard"
echo "3. Secure principal verification"
echo "It's necessary for the admin dashboard login system."