#\!/bin/bash

echo "================================================"
echo "Deploying IC-Proxy Points Fix to Digital Ocean"
echo "================================================"

# Server details
SERVER_IP="143.244.133.154"
SERVER_USER="root"
SERVER_PATH="/root/rhinospider/services/ic-proxy"

echo ""
echo "This script will deploy the updated ic-proxy server that:"
echo "1. Submits to BOTH storage and consumer canisters"
echo "2. Ensures points are properly awarded"
echo "3. Fixes the points tracking system"
echo ""
echo "Please run these commands manually:"
echo ""
echo "Step 1: Copy the updated file"
echo "scp /Users/ayanuali/development/rhinospider/services/ic-proxy/server-fixed.js root@${SERVER_IP}:${SERVER_PATH}/server-fixed.js"
echo ""
echo "Step 2: SSH into the server"
echo "ssh root@${SERVER_IP}"
echo "Password: ffGpA2saNS47qr"
echo ""
echo "Step 3: Once connected, restart the ic-proxy service"
echo "cd ${SERVER_PATH}"
echo "pm2 restart ic-proxy"
echo "pm2 logs ic-proxy --lines 20"
echo ""
echo "Step 4: Verify the deployment"
echo "curl http://${SERVER_IP}:3001/api/health"
echo ""
echo "================================================"
echo "The updated server will now:"
echo "- Submit scraped data to storage canister (for admin viewing)"
echo "- Submit scraped data to consumer canister (for points calculation)"
echo "- Award points based on data size (KB * POINTS_PER_KB)"
echo "- Apply referral bonuses when applicable"
echo "================================================"
EOF < /dev/null