name: Extension CI

on:
  push:
    branches: [main]
    paths:
      - 'apps/extension/**'
      - 'packages/**'
  pull_request:
    branches: [main]
    paths:
      - 'apps/extension/**'
      - 'packages/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Create env file
        run: |
          echo "VITE_II_URL=https://identity.ic0.app" > apps/extension/.env

      - name: Lint
        run: pnpm --filter extension lint

      - name: Test
        run: pnpm --filter extension test
        env:
          NODE_ENV: test
          CI: true

      - name: Build
        run: pnpm --filter extension build
        env:
          NODE_ENV: production

      - name: Create extension zip
        if: github.ref == 'refs/heads/main'
        run: |
          cd apps/extension/build
          zip -r ../extension.zip *

      - name: Upload Build Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: extension-build
          path: apps/extension/extension.zip

  publish:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: extension-build

      - name: Upload to Chrome Web Store
        if: false # Disabled until we have the Chrome Web Store credentials
        run: |
          echo "Chrome Web Store upload will be implemented here"
