name: Web3 Tests

on:
  push:
    paths:
      - 'packages/web3-client/**'
      - 'canisters/**'
      - 'smart-contracts/**'
  pull_request:
    paths:
      - 'packages/web3-client/**'
      - 'canisters/**'
      - 'smart-contracts/**'

jobs:
  test-web3-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Run Web3 Client Tests
        run: pnpm --filter web3-client test
        env:
          NFID_TEST_CLIENT_ID: ${{ secrets.NFID_TEST_CLIENT_ID }}
          NFID_TEST_SECRET: ${{ secrets.NFID_TEST_SECRET }}

      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          flags: web3-client
          token: ${{ secrets.CODECOV_TOKEN }}

  test-icp-canisters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install DFX
        env:
          DFX_VERSION: 0.15.1
        run: |
          echo "Installing DFX ${DFX_VERSION}..."
          sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
          dfx --version

      - name: Start DFX
        run: |
          dfx start --background
          dfx --version

      - name: Deploy Local Internet Identity
        run: |
          dfx deploy internet_identity
        working-directory: ./canisters

      - name: Run Canister Tests
        run: |
          dfx canister call internet_identity init
          dfx deploy
          dfx canister call auth run_tests
          dfx canister call storage run_tests
          dfx canister call billing run_tests
        working-directory: ./canisters

      - name: Stop DFX
        if: always()
        run: dfx stop

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: canister-test-results
          path: ./canisters/.dfx/local/canisters/*/*.test.json

  integration-tests:
    needs: [test-web3-client, test-icp-canisters]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Start Test Environment
        run: |
          dfx start --background
          dfx deploy
          pnpm test:integration

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: test-results/
          retention-days: 14
